services:
  mariadb:
    image: 'mariadb:11'
    container_name: 'mariadb'
    environment:
      - MARIADB_DATABASE=bookdb
      - MARIADB_USER=bookuser
      - MARIADB_PASSWORD=bookpass
      - MARIADB_ROOT_PASSWORD=rootpass
    ports:
      - "3306:3306"