spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bookdb
    username: bookuser
    password: bookpass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update